SELECT 
	EMPSER.C_CODEMP    AS ES_CODIGOEMPRESA,
    EMPSER.C_CODSER    AS ES_CODIGOSERVICIO,
    EMPSER.N_PRIORIDAD AS ES_PRIORIDAD,
    EMPSER.D_FECOPE    AS ES_FECHAEMPOPERA,
    EMPSER.D_FECREG    AS ES_FECHAREGISTRO,
    EMPSER.T_ACTIVO    AS ES_ACTIVO,
	
	
		EMP.C_CODEMP       AS E_CODEMPRESA,
		EMP.T_DESCRIPCION  AS E_DESCRIPCION,
		EMP.D_FECFUN       AS E_FECHAFUNDACION,
		EMP.D_FECREG       AS E_FECHAREGISTRO,
		EMP.T_NOMBRE       AS E_NOMBRE
		
		
	
		SER.C_CODSER         AS S_CODSERVICIO,
		SER.T_NOMBRE         AS S_NOMBRE,
		SER.T_SIGLA          AS S_SIGLA,
		SER.D_FECREG         AS S_FECHAREGISTRO,
		SER.T_DESCRIPCION    AS S_DESCRIPCION,
		TIPSER.C_TIPCATAL    AS S_TIPOSERVICIOID,
		TIPSER.T_DESCRIPCION AS S_TIPOSERVICIODESC
	
	
FROM AN_EMPRESA_OP_SERVICIO EMPSER

INNER JOIN AN_EMPRESA EMP ON EMPSER.C_CODEMP = EMP.C_CODEMP

INNER JOIN AN_SERVICIO SER ON EMPSER.C_CODSER = SER.C_CODSER

WHERE 

SELECT 
	GEO.C_CODGEOLOC         AS G_CODGEOLOC,
	GEO.N_LATITUD           AS G_LATITUD,
	GEO.N_LONGITUD          AS G_LONGITUD,
	TIPGEOLOC.C_TIPCATAL    AS G_TIPOGEOLOCID,
	TIPGEOLOC.T_DESCRIPCION AS G_TIPOGEOLOCDESC,
FROM AN_GEOLOC GEO
INNER JOIN AN_CATALOGO TIPGEOLOC ON GEO.GEO.T_TIPGEO = TIPGEOLOC.C_TIPCATAL

WHERE GEO.C_CODGEOLOC = #{codigoGeoLocalizacion}
AND TIPGEOLOC.C_CATALOGO = 'GEOLOC_TIPO' 

SELECT 
	FICHCLI.C_FICHCLI     AS FC_CODIGOFICHA,
	FICHCLI.N_AREATRA     AS FC_AREATRABAJO,
	FICHCLI.N_ATENCION    AS FC_ATENCION,
	FICHCLI.N_COMPLEJ     AS FC_COMPLEJIDAD,
	FICHCLI.N_FORMALI     AS FC_FORMALIDAD,
	FICHCLI.N_HOPST       AS FC_HOSPITALIDAD,
	FICHCLI.N_PRESENC     AS FC_PRESENCIA,
	FICHCLI.N_RECEP       AS FC_RECEPCION,
	FICHCLI.N_TRATO       AS FC_TRATO,
	FICHCLI.T_DESCRIPCION AS FC_DESCRIPCION
FROM AN_FICHACLIENTE FICHCLI

WHERE FICHCLI.C_FICHCLI = #{codigoFicha}


SELECT 
FICHPRO.C_FICHPROV    AS FP_CODIGOFICHA,
FICHPRO.N_ATENCION    AS FP_ATENCION,
FICHPRO.N_COHEREN     AS FP_COHERENCIA,
FICHPRO.N_CNTCTO      AS FP_CONTACTO,
FICHPRO.N_EDPROB      AS FP_EDUPROBLEMA,
FICHPRO.N_EXPROB      AS FP_EXPPROBLEMA,
FICHPRO.N_PUNTUAL     AS FP_PUNTUALIDAD,
FICHPRO.N_TIMESERV    AS FP_TIEMPOSERVICIO,
FICHPRO.T_DESCRIPCION AS FP_DESCRIPCION
FROM AN_FICHAPROVEEDOR FICHPRO

WHERE FICHPRO.C_FICHPROV = #{codigoFicha}

SELECT 
TRANS.C_CODTRAN     AS T_CODIGOTRANSACCION,
TRANS.C_ESTADO      AS T_ESTADO,
TRANS.D_FECCREA     AS T_FECHACREACION,
TRANS.D_FECTER      AS T_FECHATERMINO,
TRANS.N_MTOTOTAL    AS T_NOMTOTOTAL,
TRANS.N_CMPLEJ      AS T_COMPLEJIDAD,
TRANS.T_DESCRIPCION AS T_DESCRIPCION,
TRANS.C_CODMEDPAG   AS T_CODIGOMEDIOPAGO,
TRANS.C_TIPCATAL    AS T_TIPOMONEDAID,
TRANS.T_DESCRIPCION AS T_TIPOMONEDADESC,
TRANS.C_CODSUB      AS T_CODIGOSUBASTA

FROM AN_TRANSACCION TRANS
INNER JOIN AN_CATALOGO TIPOMONEDA ON TRANS.C_TIPMON = TIPOMONEDA.C_TIPCATAL

WHERE TIPOMONEDA.C_CATALOGO = 'MONEDA_TIPO'
AND TRANS.C_CODTRAN = #{codigoTransaccion}


SELECT 
BITTRANS.C_CODBITTRAN  AS BT_CODIGOBITTRANSACCION,
BITTRANS.T_ESTORI      AS BT_ESTADOORIGEN,
BITTRANS.T_ESTFIN      AS BT_ESTADOFINAL,
BITTRANS.D_FECMOV      AS BT_FECHAMOVIMIENTO,
BITTRANS.T_DESCRIPCION AS BT_DESCRIPCION,
BITTRANS.C_CODTRAN     AS BT_CODIGOTRANSACCION,

FROM AN_BITTRANSACCION BITTRANS

WHERE BITTRANS.C_CODTRAN = #{codigoTransaccion}
AND BITTRANS.C_CODBITTRAN = #{codigoBitTransaccion}


SELECT
MEDPAG.C_CODMEDPAG       AS MP_CODIGOMEDIOPAGO,
MEDPAG.D_FECPAG          AS MP_FECHAPAGO,
MEDPAG.N_MONTO           AS MP_MONTO,
MEDPAG.N_CUOTAS          AS MP_CUOTAS,
MEDPAG.N_MTOCTA          AS MP_MONTOCUOTA,
MEDPAG.T_DESCRIPCION     AS MP_DESCRIPCION,
TIPVIAPAGO.C_TIPCATAL    AS MP_TIPVIAPAGOID,
TIPVIAPAGO.T_DESCRIPCION AS MP_TIPVIAPAGODESC,
MEDPAG.C_CODTAR          AS MP_CODIGOTARJETA

FROM AN_MEDIOPAGO MEDPAG
INNER JOIN AN_CATALOGO TIPVIAPAGO ON MEDPAG.C_VIAPAG = TIPVIAPAGO.C_TIPCATAL

WHERE TIPOMONEDA.C_CATALOGO = 'VIAPAGO_TIPO'
AND MEDPAG.C_CODMEDPAG = #{codigoMedioPago}


SELECT
TAR.C_CODTAR             AS T_CODIGOTARJETA,
TAR.D_FECEXP             AS T_FECHAEXPIRACION,
TAR.T_NROTAR             AS T_NROTARJETA,
TIPTARJETA.C_TIPCATAL    AS T_TIPTARJETAID,
TIPTARJETA.T_DESCRIPCION AS T_TIPTARJETADESC,
ENTIDAD.C_TIPCATAL       AS T_ENTIDADID,
ENTIDAD.T_DESCRIPCION    AS T_ENTIDADDESC

FROM AN_TARJETA TAR
INNER JOIN AN_CATALOGO TIPTARJETA ON TAR.C_TIPTAR = TIPTARJETA.C_TIPCATAL
INNER JOIN AN_CATALOGO ENTIDAD ON TAR.C_ENTIDAD = ENTIDAD.C_TIPCATAL

WHERE TIPTARJETA.C_CATALOGO = 'TARJETA_TIPO'
AND TIPTARJETA.C_CATALOGO = 'ENTIDAD_COMERCIAL'
AND TAR.C_CODTAR = #{codigoTarjeta}

SELECT 
SUB.C_CODSUB      AS S_CODIGOSUBASTA,
SUB.C_ESTADO      AS S_ESTADO,
SUB.D_FECINI      AS S_FECHAINICIO,
SUB.D_FECTER      AS S_FECHATERMINO,
SUB.T_DURACION    AS S_DURACION,
SUB.N_CANTEXT     AS S_CANTIDADEXTENSIONES,
SUB.N_MTOMIN      AS S_MONTOMINIMO,
SUB.N_MTOINI      AS S_MONINICIAL,
SUB.N_MTOFINAL    AS S_MONTOFINAL,
SUB.T_DESCRIPCION AS S_DESCRIPCION,    
SUB.C_EXTEND      AS S_EXTENDIDA,
SUB.C_CODOFEG     AS S_CODIGOOFERTAGANADORA,
SUB.C_CODSER      AS S_CODIGOSERVICIO,
SUB.C_CODSOL      AS S_CODIGOSOLICITUD

FROM AN_SUBASTA SUB

WHERE SUB.C_CODSUB = #{codigoSubasta}


SELECT 
OFER.C_CODOFER  AS O_CODIGOOFERTA,
OFER.D_FECOFER  AS O_FECHAOFERTA,
OFER.N_COMISION AS O_COMISION,
OFER.N_MTOOFER  AS O_MONTOOFERTA,
OFER.C_CODSUB   AS O_CODIGOSUBASTA,
OFER.C_CODPROV  AS O_CODIGOPROVEEDOR

FROM AN_OFERTA OFER

WHERE OFER.C_CODOFER = #{}

SELECT 
PAIS.C_CODPAIS AS P_CODIGOPAIS,
PAIS.T_SIGLA   AS P_SIGLA,
PAIS.T_ABREV   AS P_ABREVIACION,
PAIS.T_NOMBRE  AS P_NOMBRE

FROM AN_PAIS PAIS

WHERE PAIS.C_CODPAIS = #{codigoPais}


SELECT 
REG.C_CODREG  AS R_CODIGOREGION,
REG.T_SIGLA   AS R_SIGLA,
REG.T_NOMBRE  AS R_NOMBRE,
REG.T_IDENT   AS R_IDENTIFICACION,
REG.C_CODPAIS AS R_CODIGOPAIS

FROM AN_REGION REG

WHERE REG.C_CODPAIS = #{codigoPais}
AND REG.C_CODREG = #{codigoRegion}


SELECT 
CIU.C_CODCIU AS C_CODIGOCIUDAD,
CIU.T_SIGLA  AS C_SIGLA,
CIU.T_NOMBRE AS C_NOMBRE,
CIU.C_CODREG AS C_CODIGOREGION

FROM AN_CIUDAD CIU

WHERE CIU.C_CODREG = #{codigoRegion}

CIU.C_CODCIU = #{codigoCiudad}

SELECT
COM.C_CODCOM AS C_CODIGOCOMUNA,
COM.T_SIGLA  AS C_SIGLA,
COM.T_NOMBRE AS C_NOMBRE,
COM.C_CODCIU AS C_CODIGOCIUDAD

FROM AN_COMUNA COM 

WHERE COM.C_CODCIU = #{codigoCiudad}
AND COM.C_CODCOM = #{codigoComuna}

SELECT 
CA.C_TIPCATAL    AS C_CODIGO,
CA.T_DESCRIPCION AS C_VALOR

FROM AN_CATALOGO CA

WHERE CA.C_CATALOGO = #{tipoCatalogo}


SELECT
CAR.C_CODCAR,
CAR.T_NOMBRE,
CAR.T_SIGLA,
CAR.T_DESCRIPCION,
CAR.T_VIGENTE
FROM AN_CARGO CAR
WHERE CAR.C_CODCAR = #{codigoCargo}


INSERT INTO AN_CARGO (
C_CODCAR,
T_NOMBRE,
T_SIGLA,
T_DESCRIPCION,
T_VIGENTE
) VALUES (
#{codigoCargo},
#{nombrecargo},
#{sigla},
#{descripcion},
#{vigente}
)

UPDATE AN_CARGO
SET T_NOMBRE = #{nombrecargo},
	T_SIGLA = #{sigla},
	T_DESCRIPCION = #{descripcion},
	T_VIGENTE = #{vigente}
WHERE C_CODCAR = #{codigoCargo}

